MODULE mod_zeros
INTERFACE zeros
MODULE PROCEDURE zeros_1, zeros_2DD, zeros_2DI, zeros_2ID, zeros_3 ! may be more
END INTERFACE zeros

CONTAINS

FUNCTION zeros_1(x)
IMPLICIT NONE
DOUBLE PRECISION, INTENT(IN) :: x
DOUBLE PRECISION, DIMENSION(INT(x),INT(x)) :: zeros_1
zeros_1 = 0;
END FUNCTION zeros_1

FUNCTION zeros_2DD(x,y)
IMPLICIT NONE
DOUBLE PRECISION, INTENT(IN) :: x, y
DOUBLE PRECISION, DIMENSION(INT(x),INT(y)) :: zeros_2DD
zeros_2DD = 0;
END FUNCTION zeros_2DD

FUNCTION zeros_2DI(x,y)
IMPLICIT NONE
DOUBLE PRECISION, INTENT(IN) :: x
INTEGER, INTENT(IN) :: y
DOUBLE PRECISION, DIMENSION(INT(x),y) :: zeros_2DI
zeros_2DI = 0;
END FUNCTION zeros_2DI

FUNCTION zeros_2ID(x,y)
IMPLICIT NONE
INTEGER, INTENT(IN) :: x
DOUBLE PRECISION, INTENT(IN) :: y
DOUBLE PRECISION, DIMENSION(x,INT(y)) :: zeros_2ID
zeros_2ID = 0;
END FUNCTION zeros_2ID

FUNCTION zeros_3(x,y,z)
IMPLICIT NONE
DOUBLE PRECISION, INTENT(IN) :: x, y, z
DOUBLE PRECISION, DIMENSION(INT(x),INT(y),INT(z)) :: zeros_3
zeros_3 = 0;
END FUNCTION zeros_3

END MODULE mod_zeros

